import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function GET() {
  // The base site URL
  const siteUrl = "https://smartlinkpilot.com";
  
  // Calculate dynamic paginations
  const PER_PAGE_LIMIT = 200;
  const publishedPostsCount = await prisma.blogPost.count({ where: { published: true } });
  const postPages = Math.ceil(publishedPostsCount / PER_PAGE_LIMIT) || 1;

  const sitemaps = [
    `${siteUrl}/page-sitemap1.xml`,
    `${siteUrl}/legal-sitemap1.xml`,
    `${siteUrl}/company-sitemap1.xml`,
    `${siteUrl}/video-sitemap1.xml`,
    `${siteUrl}/image-sitemap1.xml`
  ];
  
  // Inject the calculated post sitemaps
  for (let i = 1; i <= postPages; i++) {
    sitemaps.unshift(`${siteUrl}/post-sitemap${i}.xml`);
  }
  
  const now = new Date().toISOString();

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<?xml-stylesheet type="text/xsl" href="/main-sitemap.xsl"?>\n`;
  xml += `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`;

  for (const loc of sitemaps) {
    xml += `
  <sitemap>
    <loc>${loc}</loc>
    <lastmod>${now}</lastmod>
  </sitemap>`;
  }

  xml += `
</sitemapindex>
<!-- XML Sitemap generated by SmartLink Pilot Engine -->`;

  return new NextResponse(xml, {
    status: 200,
    headers: {
      "Content-Type": "text/xml; charset=utf-8",
      "Cache-Control": "public, s-maxage=86400, stale-while-revalidate",
    },
  });
}
