import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export async function GET(request: Request, { params }: { params: { sitemap: string } }) {
  const filename = params.sitemap;
  
  // Match the filename convention (e.g., post-sitemap1.xml -> type="post", page="1")
  const match = filename.match(/^([a-z]+)-sitemap(\d+)?\.xml$/i);
  if (!match) {
    return new NextResponse("Not Found", { status: 404 });
  }

  const type = match[1]; // post, page, legal, video, image, company
  const pageStr = match[2];
  const page = pageStr ? parseInt(pageStr, 10) : 1;
  const siteUrl = "https://smartlinkpilot.com";
  
  // Explicit User Requirement: Hard boundary representing automatic overflow architecture
  const PER_PAGE_LIMIT = 200;

  // Generate specific namespaces based on type
  let urls = "";
  const now = new Date().toISOString();

  // Route specific generators
  if (type === "page") {
    const pages = ["/", "/features", "/pricing", "/download"];
    for (const p of pages) {
      urls += `
  <url>
    <loc>${siteUrl}${p}</loc>
    <lastmod>${now}</lastmod>
  </url>`;
    }
  } else if (type === "legal") {
    const pages = ["/privacy", "/terms", "/cookies", "/disclaimer"];
    for (const p of pages) {
      urls += `
  <url>
    <loc>${siteUrl}${p}</loc>
    <lastmod>${now}</lastmod>
  </url>`;
    }
  } else if (type === "company") {
    const pages = ["/about", "/contact", "/team"];
    for (const p of pages) {
      urls += `
  <url>
    <loc>${siteUrl}${p}</loc>
    <lastmod>${now}</lastmod>
  </url>`;
    }
  } else if (type === "post") {
    // Generate posts dynamically from the active database
    const skip = (page - 1) * PER_PAGE_LIMIT;
    
    // Fetch published posts directly from the db
    const posts = await prisma.blogPost.findMany({
      where: { published: true },
      select: { slug: true, updatedAt: true },
      orderBy: { createdAt: "desc" },
      skip: skip,
      take: PER_PAGE_LIMIT
    });

    if (posts.length > 0) {
      for (const post of posts) {
        urls += `
  <url>
    <loc>${siteUrl}/blog/${post.slug}</loc>
    <lastmod>${post.updatedAt.toISOString()}</lastmod>
  </url>`;
      }
    }
  } else if (type === "video") {
     const start = (page - 1) * PER_PAGE_LIMIT + 1;
     const end = Math.min(start + 5 - 1, 5); // 5 total videos
     
     if (start <= end) {
       for (let i = start; i <= end; i++) {
         urls += `
  <url>
    <loc>${siteUrl}/videos/tutorial-${i}</loc>
    <lastmod>${now}</lastmod>
    <video:video>
      <video:thumbnail_loc>${siteUrl}/images/vid-thumb-${i}.jpg</video:thumbnail_loc>
      <video:title>SmartLink Analytics Tutorial Part ${i}</video:title>
      <video:description>An in-depth guide covering link distribution mapping ${i}</video:description>
      <video:player_loc>${siteUrl}/videos/play/${i}</video:player_loc>
    </video:video>
  </url>`;
       }
     }
  } else if (type === "image") {
     const start = (page - 1) * PER_PAGE_LIMIT + 1;
     const end = Math.min(start + 3 - 1, 3); // 3 total image sets
     
     if (start <= end) {
       for (let i = start; i <= end; i++) {
         urls += `
  <url>
    <loc>${siteUrl}/gallery/collection-${i}</loc>
    <lastmod>${now}</lastmod>
    <image:image>
      <image:loc>${siteUrl}/uploads/gallery-asset-${i}.jpg</image:loc>
      <image:title>Marketing Asset Pack ${i}</image:title>
    </image:image>
  </url>`;
       }
     }
  }

  if (!urls) {
    return new NextResponse("Not Found - No Data For Requested Index", { status: 404 });
  }

  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<?xml-stylesheet type="text/xsl" href="/main-sitemap.xsl"?>\n`;
  xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">\n`;
  xml += urls;
  xml += `\n</urlset>
<!-- XML Sitemap generated by SmartLink Pilot SEO System -->`;

  return new NextResponse(xml, {
    status: 200,
    headers: {
      "Content-Type": "text/xml; charset=utf-8",
      "Cache-Control": "public, s-maxage=86400, stale-while-revalidate",
    },
  });
}
