<?xml version="1.0" encoding="UTF-8"?><xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:kml="http://www.opengis.net/kml/2.2"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:atom="http://www.w3.org/2005/Atom">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - SmartLink Pilot</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-size: 14px;
						font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
						margin: 0;
						color: #545353;
						background-color: #f9f9f9;
					}
					a {
						color: #4F46E5;
						text-decoration: none;
					}
					h1 {
						font-size: 24px;
						font-family: Verdana,Geneva,sans-serif;
						font-weight: normal;
						margin: 0;
					}

					#description {
						background-color: #4F46E5;
						padding: 20px 40px;
						color: #fff;
						padding: 30px 30px 20px;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
					}
					#description h1,
					#description p,
					#description a {
						color: #fff;
						margin: 0;
						font-size: 1.1em;
					}
					#description h1 {
						font-size: 2.2em;
						font-weight: 700;
						margin-bottom: 0.5em;
					}
					#description p {
						margin-top: 5px;
					}
					#description a {
						border-bottom: 1px dotted;
					}

					#content {
						padding: 30px;
						background: #fff;
						max-width: 80%;
						margin: 30px auto;
						border-radius: 8px;
						box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
					}
					table {
						border: none;
						border-collapse: collapse;
						font-size: .9em;
						width: 100%;
						margin-top: 20px;
					}
					th {
						background-color: #4F46E5;
						color: #fff;
						text-align: left;
						padding: 15px 15px;
						font-size: 14px;
						font-weight: 600;
					}
					th:first-child {
					    border-top-left-radius: 6px;
					}
					th:last-child {
					    border-top-right-radius: 6px;
					}
					td {
						padding: 12px 15px;
						border-bottom: 1px solid #eee;
					}
					tbody tr:nth-child(even) {
						background-color: #f8fafc;
					}
					tbody tr:hover {
					    background-color: #f1f5f9;
					}
					table td a {
						display: block;
					}
					table td a img {
						max-height: 30px;
						margin: 6px 3px;
					}
					.expl {
					    padding-bottom: 10px;
					    color: #64748b;
					    font-weight: 500;
					}
				</style>
			</head>
			<body>
				<div id="description">
					<h1>XML Sitemap</h1>
					<p>This XML Sitemap is generated by <strong>SmartLink Pilot System</strong>. It is what search engines like Google use to crawl and re-crawl posts/pages/videos/images on the website.</p>
					<p>Learn more about <a href="http://sitemaps.org" target="_blank">XML Sitemaps</a>.</p>
				</div>
				<div id="content">
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
						<p class="expl">
							This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
						</p>
						<table id="sitemap" cellpadding="3">
							<thead>
								<tr>
									<th width="70%">Sitemap</th>
									<th width="30%">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<xsl:variable name="sitemapURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<tr>
										<td>
											<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
						<p class="expl">
							This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
						</p>
						<p class="expl">
							<a href="https://smartlinkpilot.com/sitemap_index.xml">&#8592; Sitemap Index</a>
						</p>
						<table id="sitemap" cellpadding="3">
							<thead>
								<tr>
									<th width="65%">URL</th>
									<th width="10%">Images</th>
									<th width="10%">Videos</th>
									<th title="Last Modification Time" width="15%">Last Mod.</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<xsl:variable name="itemURL">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:variable>
											<a href="{$itemURL}">
												<xsl:value-of select="sitemap:loc"/>
											</a>
										</td>
										<td>
											<xsl:value-of select="count(image:image)"/>
										</td>
										<td>
											<xsl:value-of select="count(video:video)"/>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
