import Link from "next/link";
import type { Metadata } from "next";
import { AlertTriangle, ExternalLink, BarChart2, Clock, FileText, Scale } from "lucide-react";
import { ScrollReveal } from "@/components/ScrollReveal";

export const metadata: Metadata = {
  title: "Disclaimer — SmartLink Pilot",
  description: "Read SmartLink Pilot's official Disclaimer covering general information accuracy, external links, analytics data, earnings, affiliate disclosures, and service availability.",
};

const sections = [
  {
    id: "general",
    icon: FileText,
    title: "General Disclaimer",
    content: [
      "The information provided by SmartLink Pilot (\"we,\" \"our,\" or \"us\"), operated by Mayobe Bros, on our platform and website (smartlinkpilot.com) is for general informational purposes only. All information is provided in good faith; however, we make no representation or warranty of any kind — express or implied — regarding the accuracy, adequacy, validity, reliability, or completeness of any information on the platform.",
      "While we strive to keep all content current and accurate, the rapidly evolving nature of technology means that some information may become outdated. We recommend verifying critical information through authoritative sources before making business decisions based on content found on our platform.",
    ],
  },
  {
    id: "external-links",
    icon: ExternalLink,
    title: "External Links & Shortened URLs",
    content: [
      "SmartLink Pilot is a URL shortening platform. Users of our service create short links that redirect to external websites. These destination websites are not created, operated, maintained, or endorsed by SmartLink Pilot in any way.",
      "We do not guarantee the accuracy, relevance, timeliness, safety, or completeness of any information on external websites linked through our service. The inclusion of any shortened link does not imply our endorsement, recommendation, or approval of the linked content, organization, or individual.",
      "We actively scan and monitor shortened links for malicious content, phishing, malware, and policy violations using automated systems. Links found to violate our Acceptable Use Policy are disabled promptly. However, we cannot guarantee that all harmful content will be detected before it is accessed, and we encourage users to exercise caution when clicking unknown short links.",
      "If you encounter a shortened link that appears malicious, abusive, or inappropriate, please report it immediately at support@smartlinkpilot.com with the subject line 'Abuse Report'.",
    ],
  },
  {
    id: "analytics",
    icon: BarChart2,
    title: "Analytics & Data Accuracy",
    content: [
      "SmartLink Pilot provides link analytics data including click counts, geographic distribution, device types, browser types, and referral sources. While we invest significant engineering effort to ensure the accuracy of our analytics, click counts and associated metrics are approximations and should not be treated as legally binding figures.",
      "The following factors may affect the accuracy of reported analytics data:",
    ],
    list: [
      "VPN usage, proxy servers, and Tor networks may cause geographic data to be attributed to incorrect countries",
      "Browser privacy settings, ad blockers, and privacy-focused browsers may suppress some click tracking",
      "Automated bot traffic, web crawlers, and link preview fetchers may inflate click counts",
      "Mobile data network proxies (common in Africa and Asia) may cause device/location misattribution",
      "Link previews generated by messaging apps (WhatsApp, Telegram) may register as additional clicks",
      "Network errors during redirect processing may cause some clicks to be unrecorded",
    ],
    footer: "We continuously improve our bot filtering and accuracy systems, but analytics data should be used as directional guidance rather than precise measurement. For legally binding advertising analytics, we recommend supplementing with platform-native analytics (e.g., Google Analytics on your destination page).",
  },
  {
    id: "earnings",
    icon: Scale,
    title: "Earnings & Results Disclaimer",
    content: [
      "Any reference to potential earnings, revenue growth, traffic increases, or business outcomes mentioned in our marketing materials, case studies, or platform content represents past results or estimates and does not guarantee similar outcomes for any particular user.",
      "Results from using SmartLink Pilot will vary significantly based on factors including the quality of linked content, marketing strategy, target audience, industry, geographic market, budget, and many other variables entirely outside our control.",
      "SmartLink Pilot provides a tool — the results you achieve depend on how you use it. We make no guarantees of income, traffic, conversions, or any specific business outcome from using our service.",
    ],
  },
  {
    id: "affiliate",
    icon: FileText,
    title: "Affiliate & Advertising Disclosure",
    content: [
      "SmartLink Pilot's website and platform may contain links to third-party products, services, or resources. Some of these links may be affiliate links, meaning we may receive a commission or referral fee if you click through and make a purchase — at no additional cost to you.",
      "We only link to third-party services that we genuinely believe may be useful to our users. However, our inclusion of any affiliate link does not constitute an endorsement of the product or service, and we encourage you to do your own research before making any purchase.",
      "Our platform may display advertisements through Google AdSense or similar advertising networks. These advertisements are clearly labeled and are separate from our editorial content. Third-party advertisers may use cookies to serve ads based on your prior visits to websites. You can opt out of personalized advertising at optout.aboutads.info.",
    ],
  },
  {
    id: "availability",
    icon: Clock,
    title: "Service Availability & Uptime",
    content: [
      "While SmartLink Pilot targets 99.99% uptime for our link redirect infrastructure — and has maintained this standard since launch — we cannot provide an unconditional guarantee of uninterrupted service. The following circumstances may cause temporary service degradation or unavailability:",
    ],
    list: [
      "Scheduled maintenance windows (announced at least 48 hours in advance on our status page)",
      "Emergency security patches requiring immediate deployment",
      "Third-party infrastructure failures (DNS, CDN, hosting providers)",
      "Distributed Denial of Service (DDoS) attacks",
      "Force majeure events: natural disasters, power outages, civil unrest, pandemics",
      "Regulatory actions requiring temporary service suspension",
    ],
    footer: "We are not liable for any losses (financial, reputational, or otherwise) resulting from temporary service unavailability. We recommend maintaining backup redirect strategies for mission-critical campaigns. Monitor our real-time status at status.smartlinkpilot.com.",
  },
  {
    id: "professional-advice",
    icon: Scale,
    title: "Professional & Technical Advice Disclaimer",
    content: [
      "Nothing on SmartLink Pilot constitutes professional legal, financial, tax, investment, medical, or technical advice. Content on our blog, help center, documentation, or any other part of our platform is for informational purposes only and should not be relied upon as professional guidance for your specific situation.",
      "For questions regarding data privacy compliance (GDPR, CCPA, etc.) as they apply to your specific use case, we recommend consulting a qualified privacy attorney. For tax or financial questions relating to your subscription, consult a qualified accountant.",
    ],
  },
  {
    id: "contact",
    icon: FileText,
    title: "Questions & Contact",
    content: [
      "If you have questions about this Disclaimer, wish to report a policy violation, or need clarification on any of the above points, please contact us:",
      "Email: legal@smartlinkpilot.com | Abuse reports: support@smartlinkpilot.com",
      "This Disclaimer was last updated on March 31, 2026, and should be read in conjunction with our Privacy Policy, Terms of Service, and Cookies Policy.",
    ],
  },
];

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      {/* Hero */}
      <div className="bg-gradient-to-br from-gray-800 via-gray-900 to-gray-950 dark:from-gray-900 dark:to-black py-20 relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(99,102,241,0.15),transparent_60%)]" />
        <div className="absolute bottom-0 w-full h-20 bg-gradient-to-t from-white dark:from-gray-950 to-transparent" />
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 text-center">
          <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm border border-white/20 px-4 py-2 rounded-full mb-6">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            <span className="text-white/90 text-sm font-semibold">Legal Disclaimer</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-white mb-4">Disclaimer</h1>
          <p className="text-gray-400 mb-2">Last updated: March 31, 2026</p>
          <p className="text-gray-400 text-sm max-w-xl mx-auto">Please read this Disclaimer carefully before using SmartLink Pilot. It covers important limitations and disclosures including affiliate links, analytics accuracy, and service availability.</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-16">
        {/* Alert Banner */}
        <div className="bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800/30 rounded-2xl p-5 flex items-start gap-4 mb-12">
          <AlertTriangle className="w-5 h-5 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-amber-900 dark:text-amber-200 text-sm mb-1">Important Notice</p>
            <p className="text-amber-700 dark:text-amber-300 text-sm leading-relaxed">
              This is a legal document governing your use of SmartLink Pilot. By using our service, you acknowledge that you have read and understood this Disclaimer. If you have questions, contact us at{" "}
              <a href="mailto:legal@smartlinkpilot.com" className="underline font-medium">legal@smartlinkpilot.com</a> before using the Service.
            </p>
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-10">
          {sections.map((section, idx) => (
            <ScrollReveal key={section.id} delay={idx * 100}>
            <section id={section.id} className="scroll-mt-24">
              <div className="flex items-center gap-3 mb-4 pb-3 border-b border-gray-100 dark:border-gray-800">
                <div className="w-9 h-9 bg-gray-100 dark:bg-gray-800 rounded-lg flex items-center justify-center flex-shrink-0">
                  <section.icon className="w-4.5 h-4.5 text-gray-600 dark:text-gray-400" size={18} />
                </div>
                <h2 className="text-xl font-bold text-gray-900 dark:text-white">{section.title}</h2>
              </div>

              <div className="space-y-4">
                {section.content.map((p, i) => (
                  <p key={i} className="text-gray-600 dark:text-gray-300 leading-relaxed text-sm">{p}</p>
                ))}
              </div>

              {section.list && (
                <ul className="mt-4 space-y-2 pl-1">
                  {section.list.map((item) => (
                    <li key={item} className="flex items-start gap-2.5 text-sm text-gray-600 dark:text-gray-300">
                      <span className="mt-2 w-1.5 h-1.5 bg-amber-400 rounded-full flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
              )}

              {section.footer && (
                <div className="mt-5 p-4 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl">
                  <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed italic">{section.footer}</p>
                </div>
              )}
            </section>
            </ScrollReveal>
          ))}
        </div>

        {/* Footer links */}
        <div className="mt-16 pt-8 border-t border-gray-100 dark:border-gray-800">
          <p className="text-sm text-gray-400 text-center">
            Related:{" "}
            <Link href="/privacy" className="text-blue-600 dark:text-blue-400 hover:underline">Privacy Policy</Link>
            {" · "}
            <Link href="/terms" className="text-blue-600 dark:text-blue-400 hover:underline">Terms of Service</Link>
            {" · "}
            <Link href="/cookies" className="text-blue-600 dark:text-blue-400 hover:underline">Cookies Policy</Link>
            {" · "}
            <Link href="/trust" className="text-blue-600 dark:text-blue-400 hover:underline">Trust & E-E-A-T</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
